const DEFAULT_API_ENDPOINT="https://br-delicate-glade-b46j1hyc-linkedin.compute.c-6.us-east-2.aws.neon.tech/";
const STATE_KEY="captureState",OUTBOX_KEY="outbox",ALARM="pulse-retry-outbox",VERSION=chrome.runtime.getManifest().version;
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms)),nowIso=()=>new Date().toISOString();
function safeEndpoint(value){try{const expected=new URL(DEFAULT_API_ENDPOINT),candidate=new URL(String(value||DEFAULT_API_ENDPOINT));return candidate.protocol==="https:"&&candidate.origin===expected.origin?candidate.toString():DEFAULT_API_ENDPOINT}catch{return DEFAULT_API_ENDPOINT}}
async function hardenStorage(){try{await chrome.storage.local.setAccessLevel({accessLevel:"TRUSTED_CONTEXTS"})}catch{}try{await chrome.storage.session.setAccessLevel({accessLevel:"TRUSTED_CONTEXTS"})}catch{}}
async function settings(){const s=await chrome.storage.local.get(["apiEndpoint","deviceId","deviceName","deviceToken"]);const apiEndpoint=safeEndpoint(s.apiEndpoint);if(s.apiEndpoint!==apiEndpoint)await chrome.storage.local.set({apiEndpoint});return{apiEndpoint,deviceId:s.deviceId||"",deviceName:s.deviceName||"",deviceToken:s.deviceToken||"",paired:!!s.deviceToken};}
async function updateBadge(){const n=(await outbox()).length;await chrome.action.setBadgeText({text:n?String(Math.min(n,99)):""});if(n)await chrome.action.setBadgeBackgroundColor({color:"#B54708"});}
async function setState(patch){const current=(await chrome.storage.session.get(STATE_KEY))[STATE_KEY]||{};const next={...current,...patch,updated_at:nowIso()};await chrome.storage.session.set({[STATE_KEY]:next});return next;}
async function getState(){return(await chrome.storage.session.get(STATE_KEY))[STATE_KEY]||{status:"idle"};}
async function outbox(){return(await chrome.storage.local.get(OUTBOX_KEY))[OUTBOX_KEY]||[];}
async function saveOutbox(items){await chrome.storage.local.set({[OUTBOX_KEY]:items.slice(-100)});await updateBadge();}
async function enqueue(payload,errorMessage=""){const items=await outbox();if(!items.some(x=>x.request_id===payload.request_id)){items.push({request_id:payload.request_id,payload,attempts:0,next_attempt_at:Date.now(),last_error:errorMessage});await saveOutbox(items);}return items.length;}
function apiUrl(endpoint,path){const base=endpoint.endsWith("/")?endpoint:endpoint+"/";return new URL(path.replace(/^\//,""),base).toString();}
async function pairDevice(pairingCode,deviceName){const{apiEndpoint}=await settings();const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(apiUrl(apiEndpoint,"pair"),{method:"POST",headers:{"content-type":"application/json","x-pulse-extension-version":VERSION},body:JSON.stringify({pairing_code:pairingCode,device_name:deviceName||"Chrome",extension_version:VERSION}),signal:c.signal});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.error||("API "+r.status));await chrome.storage.local.set({deviceId:body.device_id,deviceName:deviceName||"Chrome",deviceToken:body.device_token});retryOutbox().catch(()=>{});return{paired:true,device_id:body.device_id,device_name:deviceName||"Chrome"};}finally{clearTimeout(t)}}
async function authState(){const s=await settings();return{paired:s.paired,device_id:s.deviceId,device_name:s.deviceName};}
async function clearDeviceAuth(){await chrome.storage.local.remove(["deviceId","deviceToken"]);}
async function callApi(payload){const{apiEndpoint,deviceToken}=await settings();if(!deviceToken){const e=new Error("Este Chrome ainda não foi pareado com o Pulse.");e.authRequired=true;throw e;}const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(apiUrl(apiEndpoint,"capture"),{method:"POST",headers:{"content-type":"application/json","x-pulse-device-token":deviceToken,"x-pulse-extension-version":VERSION},body:JSON.stringify(payload),signal:c.signal});const body=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(body?.error||("API "+r.status));e.authRequired=r.status===401;e.nonRetryable=r.status>=400&&r.status<500&&r.status!==401&&r.status!==429;throw e;}return body;}finally{clearTimeout(t)}}
async function ensureExtractor(tabId){try{await chrome.scripting.executeScript({target:{tabId},files:["content.js"]})}catch{}}
async function sendMessageWithRetry(tabId,message,attempts=8){await ensureExtractor(tabId);let last;for(let i=0;i<attempts;i++){try{const r=await chrome.tabs.sendMessage(tabId,message);if(r?.ok)return r;last=new Error(r?.error||"Extrator não respondeu corretamente.")}catch(e){last=e}await sleep(450+i*150)}throw last||new Error("Não foi possível ler a página do LinkedIn.");}
async function waitForComplete(tabId,timeoutMs=25000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const tab=await chrome.tabs.get(tabId);if(tab?.status==="complete")return;await sleep(300)}throw new Error("A página da empresa demorou demais para carregar.");}
function companyAboutUrl(companyUrl){if(!companyUrl)return"";try{const u=new URL(companyUrl),m=u.pathname.match(/^\/company\/[^/?#]+/i);if(!m)return"";u.pathname=m[0].replace(/\/$/,"")+"/about/";u.search="";u.hash="";return u.toString()}catch{return""}}
function completePerson(person,tab){const next={...person};if(!String(next.linkedin_url||"").trim())next.linkedin_url=tab?.url||"";return next}
function quality(person,company){const req=[["Nome",person?.full_name],["URL LinkedIn",person?.linkedin_url],["Localização",person?.location],["Cargo atual",person?.current_title],["Empresa atual",person?.current_company],["Nome da empresa",company?.company_name],["Descrição",company?.description],["Site",company?.website],["Funcionários",company?.employee_count]];const missing=req.filter(([,v])=>!String(v||"").trim()).map(([k])=>k);return{score:Math.round(((req.length-missing.length)/req.length)*100),missing_fields:missing};}
async function captureCompany(companyUrl,fallbackName){const url=companyAboutUrl(companyUrl);if(!url)throw new Error("Não encontrei o link da empresa atual no perfil.");const tab=await chrome.tabs.create({url,active:false});try{await waitForComplete(tab.id);await sleep(700);const expected=new URL(companyUrl),expectedPath=expected.pathname.replace(/\/$/,"").toLowerCase();let best=null,bestScore=-1,lastError=null;for(let i=0;i<10;i++){const actual=await chrome.tabs.get(tab.id),actualUrl=new URL(actual.url||"about:blank"),actualPath=actualUrl.pathname.replace(/\/about\/?$/i,"").replace(/\/$/,"").toLowerCase();if(actualUrl.origin!==expected.origin||actualPath!==expectedPath)throw new Error("A página da empresa redirecionou para outro destino.");try{const r=await sendMessageWithRetry(tab.id,{type:"EXTRACT_COMPANY"},2);const candidate={...r.company,company_name:r.company?.company_name||fallbackName||""};const score=["company_name","description","website","employee_count"].reduce((n,k)=>n+(String(candidate?.[k]||"").trim()?1:0),0);if(score>bestScore){best=candidate;bestScore=score;}if(score===4)break;}catch(e){lastError=e;}await sleep(500);}if(!best)throw lastError||new Error("Não foi possível ler a página da empresa.");return best;}finally{try{await chrome.tabs.remove(tab.id)}catch{}}}
async function startCapture(tabId){try{await setState({status:"capturing_person",error:null,result:null,payload:null});const tab=await chrome.tabs.get(tabId);if(!tab?.url||!/^https:\/\/([a-z]{2,3}\.)?linkedin\.com\/in\//i.test(tab.url))throw new Error("Abra um perfil linkedin.com/in/... antes de capturar.");const pr=await sendMessageWithRetry(tabId,{type:"EXTRACT_PROFILE"});let person=completePerson(pr.profile,tab),companyUrl=person?._company_url||"";delete person._company_url;if(!person.full_name||!person.current_title||!person.current_company||!companyUrl)throw new Error("Nome, cargo ou empresa atual sem evidência no cabeçalho/Experiência. A captura foi interrompida para evitar dados errados.");await setState({status:"capturing_company",person});const company=await captureCompany(companyUrl,person.current_company);if(!company.company_name)throw new Error("A página da empresa não informou um nome válido.");let canonicalWarning=null;if(company.company_name.toLocaleLowerCase()!==person.current_company.toLocaleLowerCase()){canonicalWarning="O nome canônico da empresa no LinkedIn foi atualizado para "+company.company_name+".";person.current_company=company.company_name;if(person.raw_json)person.raw_json.current_company=company.company_name;}const requestId=crypto.randomUUID(),q=quality(person,company),optionalMissing=q.missing_fields.filter(x=>["Descrição","Site","Funcionários","Localização"].includes(x)),missingWarning=optionalMissing.length?"Dados opcionais não disponíveis no LinkedIn: "+optionalMissing.join(", "):null,warning=[canonicalWarning,missingWarning].filter(Boolean).join(" ")||null,payload={request_id:requestId,person,company,meta:{extension_version:VERSION,quality_score:q.score,missing_fields:q.missing_fields}};return setState({status:"ready",payload,quality:q,warning,error:null});}catch(e){await setState({status:"error",error:e?.message||"Falha ao capturar pessoa.",result:null,payload:null});throw e;}}
function applyOverrides(payload,overrides={}){const person={...payload.person,...(overrides.person||{})},company={...payload.company,...(overrides.company||{})};person.raw_json=payload.person.raw_json;person.captured_at=payload.person.captured_at;company.captured_at=payload.company.captured_at;const q=quality(person,company);return{...payload,person,company,meta:{extension_version:VERSION,quality_score:q.score,missing_fields:q.missing_fields}};}
async function saveCurrent(overrides){const state=await getState();if(!state?.payload)throw new Error("Nenhuma captura pronta para salvar.");const payload=applyOverrides(state.payload,overrides),q=quality(payload.person,payload.company);const required=[["Nome",payload.person.full_name],["URL LinkedIn",payload.person.linkedin_url],["Cargo atual",payload.person.current_title],["Empresa atual",payload.person.current_company],["Nome da empresa",payload.company.company_name]];const missing=required.filter(([,v])=>!String(v||"").trim()).map(([k])=>k);if(missing.length)throw new Error(`Revise os campos obrigatórios antes de salvar: ${missing.join(", ")}.`);if(/^(foto do perfil|profile photo|perfil linkedin)$/i.test(payload.person.full_name))throw new Error("O nome capturado não é válido.");await setState({status:"saving",payload,quality:q});try{const result=await callApi(payload);return setState({status:"saved",result,payload,outbox_count:(await outbox()).length,error:null})}catch(e){if(e.nonRetryable){await setState({status:"error",error:e.message,payload});throw e}if(e.authRequired)await clearDeviceAuth();const pending=await enqueue(payload,e.message);return setState({status:"queued",payload,outbox_count:pending,error:e.authRequired?"Pareamento expirado ou revogado; captura preservada. Faça um novo pareamento para reenviar.":"API indisponível; captura preservada localmente para reenvio automático."})}}
async function retryOutbox(){const items=await outbox();if(!items.length)return{sent:0,remaining:0};let sent=0;const keep=[];for(const item of items){if(Date.now()<(item.next_attempt_at||0)){keep.push(item);continue}try{await callApi(item.payload);sent++}catch(e){const attempts=(item.attempts||0)+(e.authRequired?0:1);if(e.authRequired){await clearDeviceAuth();keep.push({...item,last_error:e.message,next_attempt_at:Date.now()+30*60_000});continue}if(e.nonRetryable||attempts>=8)keep.push({...item,attempts,last_error:e.message,next_attempt_at:Date.now()+6*3600_000,dead:true});else{const delay=Math.min(5*60_000*2**Math.min(attempts,6),6*3600_000);keep.push({...item,attempts,last_error:e.message,next_attempt_at:Date.now()+delay})}}}await saveOutbox(keep);await setState({outbox_count:keep.length});return{sent,remaining:keep.length};}
chrome.runtime.onInstalled.addListener(async()=>{await hardenStorage();await chrome.alarms.create(ALARM,{periodInMinutes:30});await settings();await updateBadge()});
chrome.runtime.onStartup.addListener(async()=>{await hardenStorage();await chrome.alarms.create(ALARM,{periodInMinutes:30});await updateBadge();retryOutbox().catch(()=>{})});
chrome.alarms.onAlarm.addListener(a=>{if(a.name===ALARM)retryOutbox().catch(()=>{})});
chrome.runtime.onMessage.addListener((m,_s,sendResponse)=>{(async()=>{if(m?.type==="START_CAPTURE")return startCapture(m.tabId);if(m?.type==="GET_STATE")return{...(await getState()),outbox_count:(await outbox()).length};if(m?.type==="SAVE_CAPTURE")return saveCurrent(m.overrides||{});if(m?.type==="RETRY_OUTBOX")return retryOutbox();if(m?.type==="GET_SETTINGS")return settings();if(m?.type==="GET_AUTH_STATE")return authState();if(m?.type==="PAIR_DEVICE")return pairDevice(String(m.pairingCode||"").trim(),String(m.deviceName||"").trim());if(m?.type==="SET_SETTINGS"){const apiEndpoint=safeEndpoint(m.apiEndpoint);await chrome.storage.local.set({apiEndpoint});return{apiEndpoint}}return{ok:false,error:"Mensagem desconhecida."}})().then(r=>sendResponse({ok:true,...r})).catch(e=>sendResponse({ok:false,error:e?.message||"Falha interna."}));return true});
hardenStorage().catch(()=>{});updateBadge().catch(()=>{});
